### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by hacker1024** [xvrh/puppeteer-dart#134]
Are there any plans to implement null safety in this package?

**Comment by xvrh** [comment]
There is a branch with the initial experimentation. It's already in good progress but I stopped because some dependencies were not migrate yet (http etc...). I will return to that work soon.

**Comment by hacker1024** [comment]
Great!

As for `http`, the latest version in the Git repo can be used for now.

```yaml
http:
  git:
    url: 'git://github.com/dart-lang/http.git'
    ref: 'd5c678cd63c3e9c1d779a09acfa95b7e3af84665'
```
