### ISSUE TITLE
Difficulty upgrading dependencies

### ISSUE THREAD

**Issue by robbecker-wf** [xvrh/puppeteer-dart#188]
At Workiva we've been using puppeteer-dart for functional testing, but we're stuck on 1.22.0 due to a very large dependency graph. The ranges specified in 1.22.0 are one of the factors that make it challenging to upgrade our dependencies.
We could use a bridge version of this package in the 1x line that allows resolving to analyzer ^1.0.0. Using an override to analyzer ^1.0.0 I got this set of dependencies that resolves to analyzer 1.7.2
```
dependencies:
  archive: '>=2.0.0 <4.0.0'
  async: ^2.2.0
  collection: ^1.14.0
  http: '>=0.9.0 <0.13.0'
  logging: '>=0.11.3 <2.0.0'
  meta: '>=1.1.1 <1.7.0'
  path: '>=1.0.0 <2.0.0'
  petitparser: '>=2.2.0 <5.0.0'
  pool: ^1.4.0

dev_dependencies:
  analyzer:
  build_runner: '>=1.10.0 <3.0.0'
  crypto:
  dart_style: '>=1.3.6 <3.0.0'
  image: '>=2.1.3 <4.0.0'
  json_annotation: ^3.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.9.0
  shelf: '>=0.7.2 <2.0.0'
  shelf_static: '>=0.2.7 <2.0.0'
  test:
  yaml:

dependency_overrides:
  analyzer: ^1.0.0
```
This resolves with analyzer 1.7.2 but trying to run the tests locally fails. Not sure if this is going to work.

If I were suggesting changes to master I'd just open a PR but since there's no 1x branch or anything to PR to I would need a maintainer to help with this.

**Comment by xvrh** [comment]
@robbecker-wf  I created a `v1` branch. You can make a pull request against it and I will look to publish a new version to pub.dev out of it if that helps you.

That being said, v1.22 is really old and you are probably the only one still depending on it. One of your option is to fork this repo and add a git dependency to it:

```yaml
dependencies:
  puppeteer:
    git: 
      url: 'https://github.com/workiva/puppeteer-dart.git'
      ref: 'v1'
```

That way, you are not depending on me any more...
