### ISSUE TITLE
Not working in MSIX

### ISSUE THREAD

**Issue by sandip-freshcodes** [xvrh/puppeteer-dart#283]
It works properly in debug mode and in exe but when i create MSIX for uploading build on Windows Store it stopped working

Following is my MSIX configuration

```
msix_config:
  display_name: BestoSys
  publisher_display_name: BestoSys
  identity_name: BestoSys.BestoSys
  msix_version: 2.12.0.0 #windows considers first 2 numbers
  publisher: CN=3F6814EF-A698-4C52-9039-1016F0B9B84D
  install_certificate: false
  store: true
  logo_path: ./assets/images/icon_msix.png
  capabilities: internetClient
```
  
  Is it required any other capabilities to run ?
